import puppeteer from 'puppeteer-core';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const url = process.argv[2] ?? 'http://localhost:4173/';
const tag = process.argv[3] ?? 'site';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist', '--mute-audio'] });
const problems = [];
const page = await browser.newPage();
page.on('pageerror', (e) => problems.push('pageerror: ' + e.message));
page.on('requestfailed', (r) => problems.push('failed: ' + r.url()));
page.on('response', (r) => r.status() >= 400 && problems.push(r.status() + ' ' + r.url()));
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 1 });
await page.goto(url, { waitUntil: 'networkidle2' });
await sleep(4500);
await page.screenshot({ path: resolve(root, 'shots', `${tag}-desk-1.png`) });
await page.click('.game.pour');
await sleep(5200);
await page.screenshot({ path: resolve(root, 'shots', `${tag}-desk-2.png`) });
const frameOk = await page.evaluate(() => document.getElementById('screen').src);
console.log('frame shows:', frameOk, ' full-screen link:', await page.evaluate(() => document.getElementById('full').href));
const m = await browser.newPage();
m.on('pageerror', (e) => problems.push('pageerror(m): ' + e.message));
await m.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await m.goto(url, { waitUntil: 'networkidle2' });
await sleep(1200);
await m.screenshot({ path: resolve(root, 'shots', `${tag}-mob.png`), fullPage: true });
console.log('mobile loads the game in the frame:', await m.evaluate(() => !!document.getElementById('screen').getAttribute('src')));
await m.tap('.poster.pour');
await sleep(3500);
console.log('after tapping the poster, the phone is at:', m.url());
await m.screenshot({ path: resolve(root, 'shots', `${tag}-mob-game.png`) });
await browser.close();
console.log(problems.length ? 'PROBLEMS\n  ' + problems.join('\n  ') : 'no failed requests, no page errors');
